name: Request Contributorcoin for PR 
description: Automatically sends a request for Contributorcoin when a pull request is merged into the default branch
author: Contributorcoin
branding:
  icon: award
  color: purple
on:
  pull_request:
    branches: [ main, master ]
    types: [closed]
jobs:
  send-contributorcoin-request:
    name: Send Contributorcoin request

    # CONDITIONS THAT MUST BE MET
    # These are also checked on the API side, so these prevent calling the API when we know it will fail
    if: |
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.repo.visibility == 'public' &&
      (github.event.pull_request.base.repo.full_name == 'contributorcoin/contributorcoin' ||
      github.event.pull_request.base.repo.stargazers_count >= 100)

    runs-on: ubuntu-latest
    steps:
      # An additional condition check for approved reviews
      - name: Check for reviews
        id: reviews
        uses: 'jrylan/github-action-reviews-counter@main'
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
        if: steps.reviews.outputs.approved >= 1
      
      # Send API request to Contributorcoin API
      - name: Make API request
        id: request
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://api.contributorcoin.com/v1/contribute'
          method: 'POST'
          data: '{url:"${{github.event.pull_request.base.repo.html_url}}/commit/${{github.event.pull_request.merge_commit_sha}}"}'

      # Shows the API response
      - name: API response
        run: echo ${{ steps.request.outputs.response }}